@url_dev=http://localhost:3636/v1/api


### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 55f8befe03cad010a6bb2488601cb21559a65d360db0af2102ad3773fff0fb12f921ff2bf79b2b2ae298f4ad70d7c752824927c8ef205bb56d57c78d73347b2c
{
    "name" : "SHOP TRUNG 3",
    "email" : "test1234@gmail.com",
    "password" : "DepTraiCoJSai" 
}
