@url_dev=http://localhost:3636/v1/api


### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 1f87c6475f4da289116fc8eb3cea55efd7b024fbd286a115d066d3672a9a366aae1ab47a308d9d7a37d70761c8d64ee28d31c16f9617aa65b89da9a7aaf3aaa8
{
    "name" : "SHOP TRUNG 3",
    "email" : "test12345@gmail.com",
    "password" : "DepTraiCoJSai" 
}
